site_name: Akademia User Guide
site_url: http://locahost:8888
site_description: Akademia Project User Guide
copyright: |
          Copyright &copy; 2016 - 2021 <a href="https://ucamp.tech"  target="_blank" rel="noopener">CAMP, Inc.</a>

theme:
    name : readthedocs
    highlighjs: true
    hljs_languages:
        - bash
        - javascript
    features:
        - navigation.tabs

dev_addr: 'localhost:8888'
use_directory_urls: true 

nav:
- 'Home' : 'index.md'
- 'Modules' : 'modules.md' 
- 'Workflows' : 'workflows.md'

  #markdown_extensions:
  #  - pymdownx.superfences:
  #      preserve_tabs: true
  #      custom_fences:
  #       - name: mermaid
  #          class: mermaid
  #          format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search
  - mermaid2
  - git-revision-date-localized
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true

extra_css:
        #- https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
        #- https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.css
extra_javascript:
        - https://unpkg.com/mermaid/dist/mermaid.min.js
        #- https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js  
        #- https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.15.0/flowchart.min.js
        #- https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js
        #- https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js 
